layout_spectrum: 0.4712672
typography_spectrum: 0.8252628
color:
  lightness: 0.5586289
  brandStrength: 0.9548264
  saturation: 0.08500686
  rhythmicContrast: 0.1533405
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
name: Ontheprecipice
