layout_spectrum: 0.2106383
name: Ontheprecipice
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.9548264
  saturation: 0.08500686
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  lightness: 0.5586289
  rhythmicContrast: 0.1533405
typography_spectrum: 0.8252628
